[project]
name = "blog"
version = "0.1.0"
description = "Blog Project"
readme = "README.md"
authors = [
    { name = "dharmpate19", email = "pdharm774@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosmtplib>=5.1.2",
    "aiosqlite>=0.22.1",
    "alembic>=1.19.2",
    "certifi>=2026.7.22",
    "fastapi[standard]>=0.141.1",
    "git-filter-repo>=2.47.0",
    "greenlet>=3.5.5",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.5",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
]
